---
# See the documentation for more information:
# https://packit.dev/docs/configuration/
specfile_path: mrack.spec

# add or remove files that should be synced
files_to_sync:
  - mrack.spec
  - README.md
  - .packit.yaml
  - gating.yaml
  - ci.fmf
# we need to sync tmt for TF to work in Fedora updates
  - src: ./tests/smoke/*
    dest: ./tests/smoke/
  - src: ./plans/*
    dest: ./plans/

# Allow dist git reactions on packit and tdudlak commits and PRs
allowed_pr_authors:
  - packit
  - tdudlak
allowed_committers:
  - packit
  - tdudlak

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: mrack
# downstream (Fedora) RPM package name
downstream_package_name: mrack
# mrack uses tag v(ver_number) and we need to make sure packit know what to expect
# see: https://packit.dev/docs/configuration/#upstream_tag_template
upstream_tag_template: "v{version}"

sync_changelog: true

actions:
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo mrack-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"

jobs:
  - job: copr_build
    trigger: pull_request
    release_suffix: "99.dev.{PACKIT_PROJECT_BRANCH}"
    targets: [fedora-all, epel-8, epel-9]

  - job: tests
    trigger: pull_request
    identifier: "upstream-smoke"
    targets: [fedora-all, epel-8, epel-9]

  - job: copr_build
    trigger: commit
    targets: [fedora-all, epel-8, epel-9]

  - job: copr_build
    trigger: release
    owner: "@freeipa"
    project: neoave
    targets: [fedora-all, epel-8, epel-9]

  - job: propose_downstream
    trigger: release
    dist_git_branches: [fedora-all, epel-8, epel-9]

  - job: koji_build
    trigger: commit
    dist_git_branches: [fedora-all, epel-8, epel-9]

  - job: bodhi_update
    trigger: commit
    dist_git_branches: [fedora-branched, epel-8, epel-9] # rawhide updates are created automatically

  - job: tests
    fmf_url: "https://gitlab.cee.redhat.com/idm-ops/mrack-internal-tests"  #tmp change
    fmf_ref: "main"
    use_internal_tf: True
    identifier: "internal-provisioning-osp"
    trigger: pull_request
    targets: [fedora-latest-stable]
    env:
      MRACK_TEST_CASE: "provisioning-osp"

  - job: tests
    fmf_url: "https://gitlab.cee.redhat.com/idm-ops/mrack-internal-tests"
    fmf_ref: "main"
    use_internal_tf: True
    identifier: "internal-provisioning-aws"
    trigger: pull_request
    targets: [fedora-latest-stable]
    env:
      MRACK_TEST_CASE: "provisioning-aws"

  - job: tests
    fmf_url: "https://gitlab.cee.redhat.com/idm-ops/mrack-internal-tests"
    fmf_ref: "main"
    use_internal_tf: True
    identifier: "internal-provisioning-bkr-c9s-req1cpu"
    trigger: pull_request
    targets: [fedora-latest-stable]
    env:
      MRACK_TEST_CASE: "provisioning-bkr-c9s-req1cpu"

  - job: tests
    fmf_url: "https://gitlab.cee.redhat.com/idm-ops/mrack-internal-tests"
    fmf_ref: "main"
    use_internal_tf: True
    identifier: "internal-provisioning-bkr-fedora-ppc64le"
    trigger: pull_request
    targets: [fedora-latest-stable]
    env:
      MRACK_TEST_CASE: "provisioning-bkr-fedora-ppc64le"

  - job: tests
    fmf_url: "https://gitlab.cee.redhat.com/idm-ops/mrack-internal-tests"
    fmf_ref: "main"
    use_internal_tf: True
    identifier: "internal-provisioning-bkr-rhel-8-req-2048mem-2cpu"
    trigger: pull_request
    targets: [fedora-latest-stable]
    env:
      MRACK_TEST_CASE: "provisioning-bkr-rhel-8-req-2048mem-2cpu"

  - job: tests
    fmf_url: "https://gitlab.cee.redhat.com/idm-ops/mrack-internal-tests"
    fmf_ref: "main"
    use_internal_tf: True
    identifier: "internal-provisioning-bkr-rhel-9-req-4069mem"
    trigger: pull_request
    targets: [fedora-latest-stable]
    env:
      MRACK_TEST_CASE: "provisioning-bkr-rhel-9-req-4069mem"

  - job: tests
    fmf_url: "https://gitlab.cee.redhat.com/idm-ops/mrack-internal-tests"
    fmf_ref: "main"
    use_internal_tf: True
    identifier: "internal-all-providers-ssh"
    trigger: pull_request
    targets: [fedora-latest-stable]
    env:
      MRACK_TEST_CASE: "all-providers-ssh"
